// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelReservation.Models;

public partial class MealPlanRate
{
    public int MealPlanRateId { get; set; }

    public int? MealPlanId { get; set; }

    public DateOnly FromDate { get; set; }

    public DateOnly ToDate { get; set; }

    public decimal RatePerPersonPerNight { get; set; }

    public virtual MealPlan MealPlan { get; set; }
}