// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelReservation.Models;

public partial class MealPlan
{
    public int MealPlanId { get; set; }

    public string MealPlanName { get; set; }

    public virtual ICollection<MealPlanRate> MealPlanRates { get; set; } = new List<MealPlanRate>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}