// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using HotelReservation.Validation;

namespace HotelReservation.Models;

public partial class Reservation
{
    public int ReservationId { get; set; }
  

    [Required(ErrorMessage = "Name is required.")]
    [RegularExpression("^[a-zA-Z ]+$", ErrorMessage = "Name must contain only letters.")]
    public string GuestName { get; set; }

    [Required(ErrorMessage = "Email is required.")]
    [EmailAddress(ErrorMessage = "Invalid email format.")]
    public string Email { get; set; }

    [Required(ErrorMessage = "Country is required.")]
    [RegularExpression("^[a-zA-Z ]+$", ErrorMessage = "Country name must contain only letters.")]
    public string Country { get; set; }

   
    [Range(1, 100, ErrorMessage = "At least 1 adult is required.")]
    [Required(ErrorMessage = "Number of Adults is required.")]
    public int? Adults { get; set; }

    [Range(0, 100, ErrorMessage = "Children count must be 0 or more.")]
    [Required(ErrorMessage = "Number of Children is required. if there isn't please write 0")]
    public int? Children { get; set; }

    [Required(ErrorMessage = "Please Select Room Type.")]
    public int? RoomTypeId { get; set; }

    [Required(ErrorMessage = "Please Select Meal PLan.")]
    public int? MealPlanId { get; set; }
    [RequiredDate()]
    public DateOnly CheckIn { get; set; }

    [DateRange("CheckIn")]
    public DateOnly CheckOut { get; set; }

    public decimal TotalPrice { get; set; }

    public virtual MealPlan MealPlan { get; set; }

    public virtual RoomType RoomType { get; set; }
}