// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelReservation.Models;

public partial class RoomRate
{
    public int RoomRateId { get; set; }

    public int? RoomTypeId { get; set; }

    public DateOnly FromDate { get; set; }

    public DateOnly ToDate { get; set; }

    public decimal RatePerNight { get; set; }

    public virtual RoomType RoomType { get; set; }
}